name: Typecheck & Lint
on:
    push:
        branches:
            - main
        pull_request:

jobs:
    typecheck:
        name: Typecheck
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Typecheck
              run: bun run typecheck

    lint:
        name: Lint
        runs-on: ubuntu-latest
        needs: [typecheck]
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Lint
              run: bun run lint
